import React from "react";
import Head from "next/head";
import { CartBlock, Footer } from "components";

const Cart = () => {
  return (
    <>
      <Head>
        <title>Корзина || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CartBlock />
      <Footer />
    </>
  );
};

export default Cart;
