import React from "react";
import Head from "next/head";

import styles from "styles/RequestCallDone.module.scss";

const RequestCallDone = () => {
  return (
    <>
      <Head>
        <title>Запрос успешен || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.text}>
          <h1>Ваш запрос на обратный звонок успешно отправлен менеджеру!</h1>
          <img src={"/static/images/help/checked.png"} alt="done" />
        </div>
        <span>Ожидайте, в ближайшее время с Вами свяжутся :)</span>
      </div>
    </>
  );
};

export default RequestCallDone;
