import React from "react";
import Head from "next/head";
import { ProfilePageBlock } from "components";

const AutoPage = () => {
  return (
    <>
      <Head>
        <title>Мой автомобиль || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePageBlock link={"auto"} />
    </>
  );
};

export default AutoPage;
