import React from "react";
import Head from "next/head";
import { ProfileBlock } from "../../../components";

const AutoPage = () => {
  return (
    <>
      <Head>
        <title>Мой автомобиль || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileBlock />
    </>
  );
};

export default AutoPage;
