import React from "react";
import Head from "next/head";

const Delivery = () => {
  return (
    <>
      <Head>
        <title>Доставка || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Доставка</div>
    </>
  );
};

export default Delivery;
