import React from "react";
import Head from "next/head";
import { DeliveryBlock, Footer } from "components";

const Delivery = () => {
  return (
    <>
      <Head>
        <title>Доставка || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DeliveryBlock />
      <Footer />
    </>
  );
};

export default Delivery;
