import React from "react";
import Head from "next/head";
import { TowbarPersonalBlock } from "components";

const TowbarPersonalPage = () => {
  return (
    <>
      <Head>
        <title>Фаркоп || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TowbarPersonalBlock />
    </>
  );
};

export default TowbarPersonalPage;
