import React from "react";
import Head from "next/head";
import { AdminOrders } from "components/index";

const AdminDbOrdersPage = () => {
  return (
    <>
      <Head>
        <title>Управление заказами</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminOrders />
    </>
  );
};

export default AdminDbOrdersPage;
