import React from "react";
import Head from "next/head";
import { AdminAuto } from "components";

const AdminDbUsersPage = () => {
  return (
    <>
      <Head>
        <title>Управление авто</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminAuto />
    </>
  );
};

export default AdminDbUsersPage;
