import React from "react";
import Head from "next/head";
import { ManufacturersBlock } from "components";
import Footer from "components/Footer/Footer";

const Manufacturers = () => {
  return (
    <>
      <Head>
        <title>Производители || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ManufacturersBlock />
      <Footer />
    </>
  );
};

export default Manufacturers;
