import React from "react";
import Head from "next/head";

const Manufacturers = () => {
  return (
    <>
      <Head>
        <title>Производители || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </>
  );
};

export default Manufacturers;
