import React from "react";
import Head from "next/head";
import AdminOrder from "components/AdminPanel/Orders/AdminOrder";

const AdminOrderPage = () => {
  return (
    <>
      <Head>
        <title>Управление заказом || Админ-панель</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminOrder />
    </>
  );
};

export default AdminOrderPage;
