import React from "react";
import Head from "next/head";
import { SearchResults, Footer } from "components";

const SearchPage = () => {
  return (
    <>
      <Head>
        <title>Результат поиска || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchResults />
      <Footer />
    </>
  );
};

export default SearchPage;
