import React from "react";
import Head from "next/head";
import { Footer, InstallationBlock } from "components";

const Installation = () => {
  return (
    <>
      <Head>
        <title>Установка || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InstallationBlock />
      <Footer />
    </>
  );
};

export default Installation;
