import React from "react";
import Head from "next/head";
import { OrdersBlock, ProfileBlock } from "../../components";
import withAuth from "../../utils/withAuth";

const ProfilePage = () => {
  return (
    <>
      <Head>
        <title>Личный кабинет || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileBlock />
      <OrdersBlock />
    </>
  );
};

export default withAuth(ProfilePage);
