import React from "react";
import Head from "next/head";

const About = () => {
  return (
    <>
      <Head>
        <title>О нас || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>О нас</div>
    </>
  );
};

export default About;
