import React from "react";
import { CatalogAdmin } from "components";
import Head from "next/head";

const AdminCatalogPage = () => {
  return (
    <>
      <Head>
        <title>Админ-панель || Управление каталогом</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CatalogAdmin />
    </>
  );
};

export default AdminCatalogPage;
