export const json10 = {
  Treiler: [
    {
      brand: "Chevrolet",
      model: "Captiva",
      year_of_issue: "2006-2013",
      body_style: "suv",
      vendor_code: "9431",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cobalt",
      year_of_issue: "2012-2016",
      body_style: "седан",
      vendor_code: "9470",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет 4св",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cruze",
      year_of_issue: "2009-2016",
      body_style: "седан",
      vendor_code: "9450",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cruze",
      year_of_issue: "2011-",
      body_style: "хэтчбек",
      vendor_code: "9450",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lacetti",
      year_of_issue: "2004-2013",
      body_style: "седан",
      vendor_code: "9422",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lacetti",
      year_of_issue: "2004-2013",
      body_style: "универсал",
      vendor_code: "9422",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lacetti",
      year_of_issue: "2004-2013",
      body_style: "хэтчбек",
      vendor_code: "9421",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lanos",
      year_of_issue: "2005-2009",
      body_style: "хэтчбек",
      vendor_code: "9410",
      max_hor: "1100",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Orlando",
      year_of_issue: "2010-2015",
      body_style: "минивэн",
      vendor_code: "9440",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Trailblazer",
      year_of_issue: "2012-2014",
      body_style: "suv",
      vendor_code: "9460",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Espero",
      year_of_issue: "1995-1997",
      body_style: "седан",
      vendor_code: "7410",
      max_hor: "1050",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "сверление 4 отв.",
    },
    {
      brand: "Daewoo",
      model: "Gentra",
      year_of_issue: "2013-2016",
      body_style: "седан",
      vendor_code: "9422",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Matiz",
      year_of_issue: "2000-2015",
      body_style: "хэтчбек",
      vendor_code: "7420",
      max_hor: "500",
      max_ver: "35",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Nexia",
      year_of_issue: "1995-2005",
      body_style: "седан",
      vendor_code: "7410",
      max_hor: "1050",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "сверление 4 отв.",
    },
    {
      brand: "Daewoo",
      model: "Nubira",
      year_of_issue: "2003-2009",
      body_style: "универсал",
      vendor_code: "9420",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Nubira",
      year_of_issue: "2003-2013",
      body_style: "седан",
      vendor_code: "9422",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Nubira",
      year_of_issue: "2003-2013",
      body_style: "хэтчбек",
      vendor_code: "9421",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Ducato II",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Fiat",
      model: "Ducato Sollers",
      year_of_issue: "2007-2011",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Fiat",
      model: "Ducato III",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "9620",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "C-Max I",
      year_of_issue: "2003-2010",
      body_style: "минивэн",
      vendor_code: "6011",
      max_hor: "1000",
      max_ver: "40",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus I",
      year_of_issue: "1998-2004",
      body_style: "седан",
      vendor_code: "6010",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus I",
      year_of_issue: "1998-2004",
      body_style: "хэтчбек",
      vendor_code: "6010",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus II",
      year_of_issue: "2004-2011",
      body_style: "седан",
      vendor_code: "6012",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus II",
      year_of_issue: "2004-2011",
      body_style: "хэтчбек",
      vendor_code: "6011",
      max_hor: "1000",
      max_ver: "40",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus III",
      year_of_issue: "2011-2019",
      body_style: "седан",
      vendor_code: "6013",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus III",
      year_of_issue: "2011-2019",
      body_style: "хэтчбек",
      vendor_code: "6014",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus III",
      year_of_issue: "2011-2019",
      body_style: "универсал",
      vendor_code: "6015",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Fusion",
      year_of_issue: "2002-2012",
      body_style: "хэтчбек",
      vendor_code: "6030",
      max_hor: "1050",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Kuga I",
      year_of_issue: "2008-2013",
      body_style: "suv",
      vendor_code: "6041",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Kuga II",
      year_of_issue: "2013-",
      body_style: "suv",
      vendor_code: "6041",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo IV",
      year_of_issue: "2007-2015",
      body_style: "седан",
      vendor_code: "6020",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo IV",
      year_of_issue: "2007-2015",
      body_style: "универсал",
      vendor_code: "6020",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Ranger IV",
      year_of_issue: "2012-",
      body_style: "пикап",
      vendor_code: "6050",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Geely",
      model: "Atlas",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "8020",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3 Гжель",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "8120",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3+",
      year_of_issue: "2010-2016",
      body_style: "suv",
      vendor_code: "8120",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3 New",
      year_of_issue: "2014-2016",
      body_style: "suv",
      vendor_code: "8122",
      max_hor: "800",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H5 Гжель",
      year_of_issue: "2011-2016",
      body_style: "suv",
      vendor_code: "8120",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H6",
      year_of_issue: "2013-2016",
      body_style: "suv",
      vendor_code: "8121",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Haval",
      model: "F7",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "8140",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Haval",
      model: "F7x",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "8140",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Haval",
      model: "Н6",
      year_of_issue: "2015-",
      body_style: "suv",
      vendor_code: "8121",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Honda",
      model: "CR-V III",
      year_of_issue: "2007-2012",
      body_style: "suv",
      vendor_code: "7610",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Honda",
      model: "CR-V IV",
      year_of_issue: "2012-2017",
      body_style: "suv",
      vendor_code: "7611",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Accent LC",
      year_of_issue: "1999-2005",
      body_style: "седан",
      vendor_code: "7210",
      max_hor: "750",
      max_ver: "40",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Accent LC",
      year_of_issue: "1999-2005",
      body_style: "хэтчбек",
      vendor_code: "7210",
      max_hor: "750",
      max_ver: "40",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Creta",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "7260",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Elantra HD",
      year_of_issue: "2007-2012",
      body_style: "седан",
      vendor_code: "7221",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "i30 GD",
      year_of_issue: "2012-2015",
      body_style: "хэтчбек",
      vendor_code: "7352",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "i30 GD",
      year_of_issue: "2012-2017",
      body_style: "универсал",
      vendor_code: "7351",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "ix35",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "7312",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Santa Fe SM/Classic",
      year_of_issue: "2001-2013",
      body_style: "suv",
      vendor_code: "7230",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Santa Fe DM",
      year_of_issue: "2012-2018",
      body_style: "suv",
      vendor_code: "7231",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Santa Fe TM",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "7360",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Solaris",
      year_of_issue: "2010-2017",
      body_style: "седан",
      vendor_code: "7241",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Solaris",
      year_of_issue: "2010-2017",
      body_style: "хэтчбек",
      vendor_code: "7241",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Solaris",
      year_of_issue: "2017-",
      body_style: "хэтчбек",
      vendor_code: "7242",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 1",
      year_of_issue: "2004-2010",
      body_style: "suv",
      vendor_code: "7310",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 3",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "7313",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 3",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "7251",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 3",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "7251",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Iveco",
      model: "Daily IV",
      year_of_issue: "2006-2011",
      body_style: "шасси",
      vendor_code: "9650",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Kia",
      model: "Ceed II",
      year_of_issue: "2012-2018",
      body_style: "хэтчбек",
      vendor_code: "7352",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Ceed II",
      year_of_issue: "2012-2018",
      body_style: "универсал",
      vendor_code: "7351",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio II (рестайлинг)",
      year_of_issue: "2009-2011",
      body_style: "седан",
      vendor_code: "7330",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio III",
      year_of_issue: "2011-2017",
      body_style: "седан",
      vendor_code: "7240",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio III",
      year_of_issue: "2011-2017",
      body_style: "хэтчбек",
      vendor_code: "7331",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio IV",
      year_of_issue: "2017-",
      body_style: "седан",
      vendor_code: "7242",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio X-Line",
      year_of_issue: "2017-",
      body_style: "хэтчбек",
      vendor_code: "7332",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio X",
      year_of_issue: "2020-",
      body_style: "хэтчбек",
      vendor_code: "7332",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento II (рестайлинг)",
      year_of_issue: "2012-2018",
      body_style: "suv",
      vendor_code: "7231",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento III (Prime)",
      year_of_issue: "2015-",
      body_style: "suv",
      vendor_code: "7360",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Soul II",
      year_of_issue: "2014-2019",
      body_style: "хэтчбек",
      vendor_code: "7370",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Spectra",
      year_of_issue: "2000-2009",
      body_style: "седан",
      vendor_code: "7320",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage II",
      year_of_issue: "2004-2010",
      body_style: "suv",
      vendor_code: "7310",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage III",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "7312",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage IV",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "7313",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage IV",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "7251",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage IV+",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "7251",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lifan",
      model: "Х60",
      year_of_issue: "2012-",
      body_style: "suv",
      vendor_code: "8300",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара А (сверл. отв.)",
    },
    {
      brand: "Mazda",
      model: "СХ-5 I",
      year_of_issue: "2012-2017",
      body_style: "suv",
      vendor_code: "8600",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Asx",
      year_of_issue: "2010-",
      body_style: "suv",
      vendor_code: "7160",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "L200 IV",
      year_of_issue: "2006-2015",
      body_style: "пикап",
      vendor_code: "7110",
      max_hor: "2800",
      max_ver: "115",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "L200 IV",
      year_of_issue: "2006-2015",
      body_style: "пикап",
      vendor_code: "7112",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Lancer X",
      year_of_issue: "2007-2012",
      body_style: "седан",
      vendor_code: "7130",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Lancer X",
      year_of_issue: "2007-2012",
      body_style: "хэтчбек",
      vendor_code: "7130",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Lancer X",
      year_of_issue: "2007-2012",
      body_style: "универсал",
      vendor_code: "7130",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Outlander III (1-й, 2-й рейст.)",
      year_of_issue: "2012-2019",
      body_style: "suv",
      vendor_code: "7140",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Outlander III (3-й рейст.)",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "7140",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero IV",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "7120",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero Sport II",
      year_of_issue: "2008-2016",
      body_style: "suv",
      vendor_code: "7150",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Almera G11 (дорест.)",
      year_of_issue: "2013-2015",
      body_style: "седан",
      vendor_code: "7750",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Juke (2WD)",
      year_of_issue: "2010-2019",
      body_style: "suv",
      vendor_code: "7730",
      max_hor: "1150",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Juke (4WD)",
      year_of_issue: "2010-2019",
      body_style: "suv",
      vendor_code: "7730",
      max_hor: "1150",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Navara D40 (только со ступенчатым бампером)",
      year_of_issue: "2005-2015",
      body_style: "пикап",
      vendor_code: "7740",
      max_hor: "1050",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Pathfinder R51",
      year_of_issue: "2004-2014",
      body_style: "suv",
      vendor_code: "7760",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Qashqai J10",
      year_of_issue: "2007-2014",
      body_style: "suv",
      vendor_code: "7722",
      max_hor: "1250",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Qashqai J11",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "7722",
      max_hor: "1250",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Rogue T32",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "7712",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Terrano",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "9041",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "X-Trail T31",
      year_of_issue: "2007-2014",
      body_style: "suv",
      vendor_code: "7711",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "X-Trail Т32",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "7712",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "408",
      year_of_issue: "2013-",
      body_style: "седан",
      vendor_code: "9520",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Boxer",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Peugeot",
      model: "Boxer III",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Peugeot",
      model: "Boxer III",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "9620",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Partner II",
      year_of_issue: "2008-2019",
      body_style: "фургон (L1)",
      vendor_code: "9510",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Partner II",
      year_of_issue: "2008-2019",
      body_style: "фургон (L1)",
      vendor_code: "9510",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Arkana (только 4WD)",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "9070",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Duster I",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "9041",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Duster II",
      year_of_issue: "2015-2021",
      body_style: "suv",
      vendor_code: "9041",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Fluence",
      year_of_issue: "2009-",
      body_style: "седан",
      vendor_code: "9020",
      max_hor: "950",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Kaptur",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "9061",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Logan I",
      year_of_issue: "2005-2014",
      body_style: "седан",
      vendor_code: "9010",
      max_hor: "950",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Megane III",
      year_of_issue: "2008-2016",
      body_style: "хэтчбек",
      vendor_code: "9050",
      max_hor: "1050",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero I",
      year_of_issue: "2009-2014",
      body_style: "хэтчбек",
      vendor_code: "9030",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero Stepway I",
      year_of_issue: "2009-2014",
      body_style: "хэтчбек",
      vendor_code: "9030",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "9031",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero Stepway II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "9031",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Fabia 5J",
      year_of_issue: "2008-2014",
      body_style: "хэтчбек",
      vendor_code: "9731",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Fabia 5J",
      year_of_issue: "2008-2014",
      body_style: "универсал",
      vendor_code: "9730",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia II",
      year_of_issue: "2004-2013",
      body_style: "универсал",
      vendor_code: "9711",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia II Scout",
      year_of_issue: "2008-2013",
      body_style: "универсал",
      vendor_code: "9711",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia II",
      year_of_issue: "2008-2013",
      body_style: "хэтчбек",
      vendor_code: "9710",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia III",
      year_of_issue: "2013-2020",
      body_style: "хэтчбек",
      vendor_code: "9712",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia III",
      year_of_issue: "2013-2020",
      body_style: "универсал",
      vendor_code: "9712",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Rapid",
      year_of_issue: "2013-",
      body_style: "хэтчбек",
      vendor_code: "9740",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Superb III",
      year_of_issue: "2015-",
      body_style: "седан",
      vendor_code: "9712",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Yeti",
      year_of_issue: "2009-2018",
      body_style: "suv",
      vendor_code: "9720",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Actyon II",
      year_of_issue: "2011-2015",
      body_style: "suv",
      vendor_code: "7520",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Kyron",
      year_of_issue: "2005-2016",
      body_style: "suv",
      vendor_code: "7510",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Kyron",
      year_of_issue: "2005-2016",
      body_style: "suv",
      vendor_code: "7510.K2",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "SsangYong",
      model: "Rexton Y250",
      year_of_issue: "2006-2017",
      body_style: "suv",
      vendor_code: "7500",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Subaru",
      model: "Forester III",
      year_of_issue: "2008-2013",
      body_style: "suv",
      vendor_code: "8500",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester IV (дорестайлинг)",
      year_of_issue: "2013-2016",
      body_style: "suv",
      vendor_code: "8501",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester V",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "8502",
      max_hor: "1150",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Impreza III",
      year_of_issue: "2011-2014",
      body_style: "хэтчбек",
      vendor_code: "8510",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Outback V",
      year_of_issue: "2015-",
      body_style: "универсал",
      vendor_code: "8520",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Grand Vitara",
      year_of_issue: "2005-2016",
      body_style: "suv, 5 дв.",
      vendor_code: "7900",
      max_hor: "1200",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Vitara III",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "7910",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Amarok",
      year_of_issue: "2010-",
      body_style: "пикап",
      vendor_code: "9160",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Jetta VI",
      year_of_issue: "2011-2018",
      body_style: "седан",
      vendor_code: "9170",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo sedan",
      year_of_issue: "2010-",
      body_style: "седан",
      vendor_code: "9130",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo liftback",
      year_of_issue: "2020-",
      body_style: "хэтчбек",
      vendor_code: "9130",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan I",
      year_of_issue: "2007-2016",
      body_style: "suv",
      vendor_code: "9151",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan II",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "9151",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Touareg III",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "9140",
      max_hor: "1300",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E170",
      year_of_issue: "2013-2019",
      body_style: "седан",
      vendor_code: "7840",
      max_hor: "1100",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Fortuner II (кроме авто с функцией “Свободные руки”)",
      year_of_issue: "2017-",
      body_style: "suv",
      vendor_code: "7870",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Highlander XU50",
      year_of_issue: "2014-2020",
      body_style: "suv",
      vendor_code: "7850",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Hilux VII (c силовым брусом)",
      year_of_issue: "2008-2015",
      body_style: "пикап",
      vendor_code: "7860",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 100 VX (10м)",
      year_of_issue: "1998-2008",
      body_style: "suv",
      vendor_code: "7820",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 120",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "7810",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 150",
      year_of_issue: "2009-",
      body_style: "suv",
      vendor_code: "7810",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 200",
      year_of_issue: "2007-2014",
      body_style: "suv",
      vendor_code: "7821",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 XA20",
      year_of_issue: "2000-2006",
      body_style: "suv",
      vendor_code: "7831",
      max_hor: "1000",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 XA30 (кроме USA)",
      year_of_issue: "2006-2013",
      body_style: "suv",
      vendor_code: "7830",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 IV",
      year_of_issue: "2013-2019",
      body_style: "suv",
      vendor_code: "7833",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 V",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "7834",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Opel",
      model: "Antara I",
      year_of_issue: "2006-2013",
      body_style: "suv",
      vendor_code: "9910",
      max_hor: "1150",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Opel",
      model: "Astra J",
      year_of_issue: "2009-2015",
      body_style: "хэтчбек",
      vendor_code: "9931",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Opel",
      model: "Zafira B",
      year_of_issue: "2005-2012",
      body_style: "минивэн",
      vendor_code: "9920",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "Berlingo II",
      year_of_issue: "2008-2019",
      body_style: "фургон (L1)",
      vendor_code: "9510",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "Jumper I",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Citroen",
      model: "Jumper II",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "9610",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Citroen",
      model: "Jumper II",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "9620",
      max_hor: "1200",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2011-2018",
      body_style: "седан",
      vendor_code: "2190",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2016-2020",
      body_style: "седан",
      vendor_code: "2191",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2016-2020",
      body_style: "хэтчбек",
      vendor_code: "2191",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Largus",
      year_of_issue: "2012-",
      body_style: "универсал",
      vendor_code: "2011",
      max_hor: "950",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Largus Cross",
      year_of_issue: "2015-",
      body_style: "универсал",
      vendor_code: "2011",
      max_hor: "950",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Niva",
      year_of_issue: "1977-",
      body_style: "хэтчбек",
      vendor_code: "2121",
      max_hor: "930",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "Lada",
      model: "Vesta",
      year_of_issue: "2016-",
      body_style: "седан",
      vendor_code: "2180",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Vesta",
      year_of_issue: "2017-",
      body_style: "универсал",
      vendor_code: "2180",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Vesta Cross",
      year_of_issue: "2018-2020",
      body_style: "универсал",
      vendor_code: "2180",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "X-Ray",
      year_of_issue: "2016-",
      body_style: "универсал",
      vendor_code: "2240",
      max_hor: "800",
      max_ver: "40",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "X-Ray Cross",
      year_of_issue: "2018-",
      body_style: "универсал",
      vendor_code: "2241",
      max_hor: "800",
      max_ver: "40",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
  ],
};
