export const json11 = {
  Avtos: [
    {
      brand: "AUDI",
      model: "80 B3",
      year_of_issue: "1986-1991",
      body_style: "седан",
      vendor_code: "AU 01",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "AUDI",
      model: "80 B4",
      year_of_issue: "1991-1996",
      body_style: "седан",
      vendor_code: "AU 03",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "AUDI",
      model: "100 С3",
      year_of_issue: "1982-1990",
      body_style: "седан",
      vendor_code: "AU 02",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "AUDI",
      model: "А3 8L",
      year_of_issue: "1996-2003",
      body_style: "хэтчбек",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "AUDI",
      model: "Q3 8U",
      year_of_issue: "2011-2019",
      body_style: "suv",
      vendor_code: "VW 35",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "AUDI",
      model: "Q5 8R",
      year_of_issue: "2008-2016",
      body_style: "suv",
      vendor_code: "AU 04",
      max_hor: "2400",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "AUDI",
      model: "Q7 4L",
      year_of_issue: "2005-2015",
      body_style: "suv",
      vendor_code: "AU 05",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "BMW",
      model: "Х1 E84",
      year_of_issue: "2009-2015",
      body_style: "suv",
      vendor_code: "BM 04",
      max_hor: "1600",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "BMW",
      model: "Х3 F25",
      year_of_issue: "2010-2017",
      body_style: "suv",
      vendor_code: "BM 03",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "BMW",
      model: "Х4 F26",
      year_of_issue: "2014-2018",
      body_style: "suv",
      vendor_code: "BM 03",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "BMW",
      model: "Х5 E53",
      year_of_issue: "2000-2006",
      body_style: "suv",
      vendor_code: "BM 01",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "BMW",
      model: "Х5 E70",
      year_of_issue: "2006-2013",
      body_style: "suv",
      vendor_code: "BM 02",
      max_hor: "2500",
      max_ver: "125",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Aveo",
      year_of_issue: "2002-2012",
      body_style: "седан",
      vendor_code: "CV 07",
      max_hor: "750",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Aveo",
      year_of_issue: "2002-2012",
      body_style: "хэтчбек",
      vendor_code: "CV 06",
      max_hor: "1200",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Aveo",
      year_of_issue: "2012-2019",
      body_style: "седан",
      vendor_code: "CV 11",
      max_hor: "1250",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Captiva",
      year_of_issue: "2006-2013",
      body_style: "suv",
      vendor_code: "CV 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cobalt",
      year_of_issue: "2012-2016",
      body_style: "седан",
      vendor_code: "CV 12",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cruze",
      year_of_issue: "2009-2016",
      body_style: "седан",
      vendor_code: "CV 08",
      max_hor: "1800",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Cruze",
      year_of_issue: "2013-2016",
      body_style: "универсал",
      vendor_code: "CV 14",
      max_hor: "1800",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lacetti",
      year_of_issue: "2004-2013",
      body_style: "седан",
      vendor_code: "DW 07",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Lanos",
      year_of_issue: "2005-2009",
      body_style: "седан",
      vendor_code: "CV 01",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Rezzo",
      year_of_issue: "2004-2009",
      body_style: "минивэн",
      vendor_code: "DW 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Chevrolet",
      model: "Spark M300",
      year_of_issue: "2011-2015",
      body_style: "хэтчбек",
      vendor_code: "CV 10",
      max_hor: "750",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Gentra",
      year_of_issue: "2013-2016",
      body_style: "седан",
      vendor_code: "DW 07",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Kalos",
      year_of_issue: "2002-2006",
      body_style: "седан",
      vendor_code: "DW 06",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Lanos",
      year_of_issue: "1997-2002",
      body_style: "седан",
      vendor_code: "CV 01",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Matiz",
      year_of_issue: "2000-2015",
      body_style: "хэтчбек",
      vendor_code: "DW 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Nexia",
      year_of_issue: "1995-2010",
      body_style: "седан",
      vendor_code: "DW 03",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Nubira",
      year_of_issue: "2003-2013",
      body_style: "универсал",
      vendor_code: "CV 04",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Rezzo",
      year_of_issue: "2000-2004",
      body_style: "минивэн",
      vendor_code: "DW 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Daewoo",
      model: "Tacuma",
      year_of_issue: "2000-2004",
      body_style: "минивэн",
      vendor_code: "DW 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Albea",
      year_of_issue: "2015-",
      body_style: "седан",
      vendor_code: "FA 01",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Doblo I",
      year_of_issue: "2001-2010",
      body_style: "минивэн",
      vendor_code: "FA 02",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Ducato II",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "FA 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Ducato Sollers",
      year_of_issue: "2007-2011",
      body_style: "фургон",
      vendor_code: "FA 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Fiat",
      model: "Ducato III",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "FA 06",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Fiat",
      model: "Grande Punto",
      year_of_issue: "2005-2018",
      body_style: "хэтчбек",
      vendor_code: "FA 03",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "C-Max I",
      year_of_issue: "2003-2010",
      body_style: "минивэн",
      vendor_code: "FD 19",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "C-Max II",
      year_of_issue: "2010-2019",
      body_style: "минивэн",
      vendor_code: "FD 27",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "C-Max II (в т.ч. Grand)",
      year_of_issue: "2010-2019",
      body_style: "минивэн",
      vendor_code: "FD 27",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Escape I (рестайлинг)",
      year_of_issue: "2004-2007",
      body_style: "suv",
      vendor_code: "FD 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus I",
      year_of_issue: "1998-2004",
      body_style: "седан",
      vendor_code: "FD 02",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus I",
      year_of_issue: "1998-2004",
      body_style: "хэтчбек",
      vendor_code: "FD 02",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus I",
      year_of_issue: "1998-2004",
      body_style: "универсал",
      vendor_code: "FD 14",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus II",
      year_of_issue: "2004-2011",
      body_style: "седан",
      vendor_code: "FD 20",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus II",
      year_of_issue: "2004-2011",
      body_style: "хэтчбек",
      vendor_code: "FD 19",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus II",
      year_of_issue: "2004-2011",
      body_style: "универсал",
      vendor_code: "FD 25",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus III",
      year_of_issue: "2011-2019",
      body_style: "хэтчбек",
      vendor_code: "FD 19",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Focus III",
      year_of_issue: "2011-2019",
      body_style: "универсал",
      vendor_code: "FD 29",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Fusion",
      year_of_issue: "2002-2012",
      body_style: "хэтчбек",
      vendor_code: "FD 21",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Galaxy I (рестайлинг)",
      year_of_issue: "2000-2006",
      body_style: "минивэн",
      vendor_code: "VW 22",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Kuga I",
      year_of_issue: "2008-2013",
      body_style: "suv",
      vendor_code: "FD 22",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Kuga II",
      year_of_issue: "2013-",
      body_style: "suv",
      vendor_code: "FD 31",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Maverick II",
      year_of_issue: "2004-2007",
      body_style: "suv",
      vendor_code: "FD 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo IV",
      year_of_issue: "2007-2015",
      body_style: "седан",
      vendor_code: "FD 23",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo IV",
      year_of_issue: "2007-2015",
      body_style: "универсал",
      vendor_code: "FD 23",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo V",
      year_of_issue: "2014-",
      body_style: "седан",
      vendor_code: "FD 33",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Mondeo V",
      year_of_issue: "2014-",
      body_style: "универсал",
      vendor_code: "FD 33",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Ranger I, II",
      year_of_issue: "1999-2007",
      body_style: "пикап",
      vendor_code: "FD 28",
      max_hor: "2800",
      max_ver: "115",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Ford",
      model: "S-Max I",
      year_of_issue: "2006-2015",
      body_style: "минивэн",
      vendor_code: "FD 15",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Tourneo Custom",
      year_of_issue: "2013-",
      body_style: "минивэн",
      vendor_code: "FD 30",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Transit V",
      year_of_issue: "1994-2000",
      body_style: "фургон",
      vendor_code: "FD 05",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Ford",
      model: "Transit VI, VII",
      year_of_issue: "2000-2014",
      body_style: "фургон",
      vendor_code: "FD 26",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Ford",
      model: "Transit VI, VII",
      year_of_issue: "2000-2014",
      body_style: "шасси",
      vendor_code: "FD 34",
      max_hor: "3000",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Ford",
      model: "Transit VIII",
      year_of_issue: "2014-",
      body_style: "фургон",
      vendor_code: "FD 32",
      max_hor: "2500",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Geely",
      model: "MK",
      year_of_issue: "2006-2015",
      body_style: "седан",
      vendor_code: "GL 01",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Deer",
      year_of_issue: "2005-2009",
      body_style: "пикап",
      vendor_code: "GW 01",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3",
      year_of_issue: "2005-2010",
      body_style: "suv",
      vendor_code: "GW 12",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3",
      year_of_issue: "2005-2010",
      body_style: "suv",
      vendor_code: "GW 03",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3",
      year_of_issue: "2005-2010",
      body_style: "suv",
      vendor_code: "GW 05",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3+",
      year_of_issue: "2010-2016",
      body_style: "suv",
      vendor_code: "GW 08",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3+",
      year_of_issue: "2010-2016",
      body_style: "suv",
      vendor_code: "GW 12",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H3 New",
      year_of_issue: "2014-2016",
      body_style: "suv",
      vendor_code: "GW 12",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H5",
      year_of_issue: "2011-2016",
      body_style: "suv",
      vendor_code: "GW 05",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H5",
      year_of_issue: "2011-2016",
      body_style: "suv",
      vendor_code: "GW 12",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover H6",
      year_of_issue: "2013-2016",
      body_style: "suv",
      vendor_code: "GW 11",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover M2",
      year_of_issue: "2013-2016",
      body_style: "suv",
      vendor_code: "GW 09",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Hover M4",
      year_of_issue: "2013-2016",
      body_style: "suv",
      vendor_code: "GW 10",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Safe",
      year_of_issue: "2005-2009",
      body_style: "suv",
      vendor_code: "GW 07",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Sailor",
      year_of_issue: "2006-2011",
      body_style: "пикап",
      vendor_code: "GW 04",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Great Wall",
      model: "Wingle 3",
      year_of_issue: "2007-2011",
      body_style: "пикап",
      vendor_code: "GW 06",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Haval",
      model: "Н2",
      year_of_issue: "2015-",
      body_style: "suv",
      vendor_code: "HV 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Haval",
      model: "Н6",
      year_of_issue: "2015-",
      body_style: "suv",
      vendor_code: "HV 01",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Honda",
      model: "CR-V I",
      year_of_issue: "1997-2002",
      body_style: "suv",
      vendor_code: "HN 01",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Honda",
      model: "CR-V II",
      year_of_issue: "2002-2006",
      body_style: "suv",
      vendor_code: "HN 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Creta",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "HY 29",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "ix35",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "HY 22",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Santa Fe CM",
      year_of_issue: "2006-2012",
      body_style: "suv",
      vendor_code: "HY 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Santa Fe DM",
      year_of_issue: "2012-2018",
      body_style: "suv",
      vendor_code: "KI 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 1",
      year_of_issue: "2004-2010",
      body_style: "suv",
      vendor_code: "KI 16",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Hyundai",
      model: "Tucson 3",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "HY 28",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Infiniti",
      model: "QX4",
      year_of_issue: "1996-2003",
      body_style: "suv",
      vendor_code: "NS 18",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Isuzu",
      model: "D-Max II",
      year_of_issue: "2007-2012",
      body_style: "пикап",
      vendor_code: "IS 01",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Isuzu",
      model: "D-Max II",
      year_of_issue: "2007-2012",
      body_style: "пикап",
      vendor_code: "IS 02",
      max_hor: "3000",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "бампер трубой",
    },
    {
      brand: "Isuzu",
      model: "D-Max II (рестайлинг)",
      year_of_issue: "2012-",
      body_style: "пикап",
      vendor_code: "IS 03",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Jeep",
      model: "Compass",
      year_of_issue: "2006-2017",
      body_style: "suv",
      vendor_code: "JW 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Jeep",
      model: "Grand Cherokee WK2",
      year_of_issue: "2010-",
      body_style: "suv",
      vendor_code: "JW 03",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Jeep",
      model: "Liberty",
      year_of_issue: "2006-2017",
      body_style: "suv",
      vendor_code: "JW 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Jeep",
      model: "Patriot",
      year_of_issue: "2006-2017",
      body_style: "suv",
      vendor_code: "JW 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Jeep",
      model: "Wrangler TJ",
      year_of_issue: "1996-2007",
      body_style: "suv",
      vendor_code: "JW 01",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Ceed I",
      year_of_issue: "2006-2012",
      body_style: "хэтчбек",
      vendor_code: "KI 13",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Ceed I",
      year_of_issue: "2006-2012",
      body_style: "универсал",
      vendor_code: "KI 15",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Ceed II",
      year_of_issue: "2012-2018",
      body_style: "хэтчбек",
      vendor_code: "KI 27",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Ceed II",
      year_of_issue: "2012-2018",
      body_style: "универсал",
      vendor_code: "KI 26",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Cerato III",
      year_of_issue: "2013-2018",
      body_style: "седан",
      vendor_code: "KI 25",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Mohave",
      year_of_issue: "2008-2018",
      body_style: "suv",
      vendor_code: "KI 21",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара G",
    },
    {
      brand: "Kia",
      model: "Optima IV",
      year_of_issue: "2016-2020",
      body_style: "седан",
      vendor_code: "KI 33",
      max_hor: "1800",
      max_ver: "85",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Optima IV",
      year_of_issue: "2016-2020",
      body_style: "универсал",
      vendor_code: "KI 33",
      max_hor: "1800",
      max_ver: "85",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Picanto I",
      year_of_issue: "2003-2011",
      body_style: "хэтчбек",
      vendor_code: "KI 20",
      max_hor: "700",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Picanto II",
      year_of_issue: "2011-2017",
      body_style: "хэтчбек",
      vendor_code: "KI 23",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio II (рестайлинг)",
      year_of_issue: "2009-2011",
      body_style: "хэтчбек",
      vendor_code: "KI 19",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio III",
      year_of_issue: "2011-2017",
      body_style: "седан",
      vendor_code: "HY 23",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio III",
      year_of_issue: "2011-2017",
      body_style: "седан",
      vendor_code: "KI 22",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio III",
      year_of_issue: "2011-2017",
      body_style: "хэтчбек",
      vendor_code: "KI 29",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio X-Line",
      year_of_issue: "2017-",
      body_style: "хэтчбек",
      vendor_code: "KI 35",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Rio X",
      year_of_issue: "2020-",
      body_style: "хэтчбек",
      vendor_code: "KI 35",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sephia II",
      year_of_issue: "1998-2004",
      body_style: "седан",
      vendor_code: "KI 14",
      max_hor: "1350",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento I (рестайлинг)",
      year_of_issue: "2006-2009",
      body_style: "suv",
      vendor_code: "KI 12",
      max_hor: "1500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento II (дорестайлинг)",
      year_of_issue: "2009-2012",
      body_style: "suv",
      vendor_code: "KI 17",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento II (рестайлинг)",
      year_of_issue: "2012-2018",
      body_style: "suv",
      vendor_code: "KI 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sorento III (Prime)",
      year_of_issue: "2015-",
      body_style: "suv",
      vendor_code: "KI 31",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Soul I",
      year_of_issue: "2008-2014",
      body_style: "хэтчбек",
      vendor_code: "KI 18",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Soul II",
      year_of_issue: "2014-2019",
      body_style: "хэтчбек",
      vendor_code: "KI 28",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Spectra",
      year_of_issue: "2000-2009",
      body_style: "седан",
      vendor_code: "KI 14",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage I",
      year_of_issue: "1995-2004",
      body_style: "suv",
      vendor_code: "KI 11",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "Kia",
      model: "Grand Sportage",
      year_of_issue: "2000-2005",
      body_style: "suv",
      vendor_code: "KI 06",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "Kia",
      model: "Sportage II",
      year_of_issue: "2004-2010",
      body_style: "suv",
      vendor_code: "KI 16",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage III",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "HY 22",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Kia",
      model: "Sportage IV",
      year_of_issue: "2015-2018",
      body_style: "suv",
      vendor_code: "HY 28",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Land Rover",
      model: "Freelander II",
      year_of_issue: "2006-2015",
      body_style: "suv",
      vendor_code: "LD 01",
      max_hor: "2000",
      max_ver: "125",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "GX 470",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "TY 42",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "GX 470",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "TY 21",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "GX 460",
      year_of_issue: "2009-",
      body_style: "suv",
      vendor_code: "TY 42",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "GX 460",
      year_of_issue: "2009-",
      body_style: "suv",
      vendor_code: "TY 21",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "LX 570",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "TY 28",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "NX",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "LX 04",
      max_hor: "1500",
      max_ver: "80",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "RX I",
      year_of_issue: "1998-2003",
      body_style: "suv",
      vendor_code: "LX 01",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lexus",
      model: "RX II",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "LX 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lifan",
      model: "620",
      year_of_issue: "2010-",
      body_style: "седан",
      vendor_code: "LF 01",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lifan",
      model: "Cebrium",
      year_of_issue: "2014-",
      body_style: "седан",
      vendor_code: "LF 03",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lifan",
      model: "Solano",
      year_of_issue: "2010-",
      body_style: "седан",
      vendor_code: "LF 01",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lifan",
      model: "Х60",
      year_of_issue: "2012-",
      body_style: "suv",
      vendor_code: "LF 02",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mazda",
      model: "5 CR",
      year_of_issue: "2005-2010",
      body_style: "минивэн",
      vendor_code: "MZ 02",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mazda",
      model: "6 GJ",
      year_of_issue: "2012-",
      body_style: "седан",
      vendor_code: "MZ 03",
      max_hor: "1750",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mazda",
      model: "СХ-5 I",
      year_of_issue: "2012-2017",
      body_style: "suv",
      vendor_code: "MZ 01",
      max_hor: "1750",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mazda",
      model: "Tribute I (рестайлинг)",
      year_of_issue: "2004-2007",
      body_style: "suv",
      vendor_code: "FD 24",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "GL-Class x164",
      year_of_issue: "2006-2012",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "GL-Class x166",
      year_of_issue: "2012-2016",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "GLE-Class w166",
      year_of_issue: "2015-2019",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "GLK-Class x204",
      year_of_issue: "2008-2015",
      body_style: "suv",
      vendor_code: "MB 08",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "GLS-Class x166",
      year_of_issue: "2016-2019",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "M-Class w164",
      year_of_issue: "2005-2012",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "M-Class w166",
      year_of_issue: "2012-2015",
      body_style: "suv",
      vendor_code: "MB 07",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "Sprinter II (со ступ.)",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "MB 04",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Mercedes-Benz",
      model: "Sprinter II (без ступ.)",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "MB 06",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Mercedes-Benz",
      model: "Viano w638",
      year_of_issue: "1996-2003",
      body_style: "минивэн",
      vendor_code: "MB 03",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "Viano w639",
      year_of_issue: "2003-2014",
      body_style: "минивэн",
      vendor_code: "MB 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "Vito w638",
      year_of_issue: "1996-2003",
      body_style: "минивэн",
      vendor_code: "MB 03",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mercedes-Benz",
      model: "Vito w639",
      year_of_issue: "2003-2014",
      body_style: "минивэн",
      vendor_code: "MB 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Asx",
      year_of_issue: "2010-",
      body_style: "suv",
      vendor_code: "MI 23",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Galant IX",
      year_of_issue: "2004-2012",
      body_style: "седан",
      vendor_code: "MI 17",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Galant IX",
      year_of_issue: "2004-2012",
      body_style: "хэтчбек",
      vendor_code: "MI 17",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "L200 IV",
      year_of_issue: "2006-2015",
      body_style: "пикап",
      vendor_code: "MI 18",
      max_hor: "2500",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "L200 IV",
      year_of_issue: "2006-2015",
      body_style: "пикап",
      vendor_code: "MI 28",
      max_hor: "2500",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "L200 V",
      year_of_issue: "2015-",
      body_style: "пикап",
      vendor_code: "MI 28",
      max_hor: "2500",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Lancer IX",
      year_of_issue: "2003-2007",
      body_style: "седан",
      vendor_code: "MI 22",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Lancer X",
      year_of_issue: "2007-2012",
      body_style: "седан",
      vendor_code: "MI 19",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Outlander I",
      year_of_issue: "2003-2007",
      body_style: "suv",
      vendor_code: "MI 24",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Outlander XL",
      year_of_issue: "2007-2012",
      body_style: "suv",
      vendor_code: "MI 21",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Outlander III (1-й, 2-й рейст.)",
      year_of_issue: "2012-2019",
      body_style: "suv",
      vendor_code: "MI 25",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero III",
      year_of_issue: "2000-2007",
      body_style: "suv",
      vendor_code: "MI 26",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero IV",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "MI 26",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero Sport I",
      year_of_issue: "1998-2008",
      body_style: "suv",
      vendor_code: "MI 15",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Mitsubishi",
      model: "Pajero Sport II",
      year_of_issue: "2008-2016",
      body_style: "suv",
      vendor_code: "MI 20",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Nissan",
      model: "Almera Classic",
      year_of_issue: "2000-2005",
      body_style: "седан",
      vendor_code: "NS 14",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Almera G11",
      year_of_issue: "2013-",
      body_style: "седан",
      vendor_code: "NS 24",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Juke (2WD)",
      year_of_issue: "2010-2019",
      body_style: "suv",
      vendor_code: "NS 26",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Kubistar",
      year_of_issue: "2003-2009",
      body_style: "фургон",
      vendor_code: "RN 05",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Murano Z52",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "NS 33",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Navara D40",
      year_of_issue: "2005-2015",
      body_style: "пикап",
      vendor_code: "NS 16",
      max_hor: "3000",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Note E11",
      year_of_issue: "2006-2012",
      body_style: "хэтчбек",
      vendor_code: "NS 19",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "NP300",
      year_of_issue: "2007-2013",
      body_style: "пикап",
      vendor_code: "NS 22",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Pathfinder R50",
      year_of_issue: "1996-2004",
      body_style: "suv",
      vendor_code: "NS 18",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Pathfinder R51",
      year_of_issue: "2004-2014",
      body_style: "suv",
      vendor_code: "NS 21",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Pathfinder R52",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "NS 30",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Patrol Y61",
      year_of_issue: "1997-2010",
      body_style: "suv",
      vendor_code: "NS 20",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Patrol Y61",
      year_of_issue: "1997-2010",
      body_style: "suv",
      vendor_code: "NS 12",
      max_hor: "2500",
      max_ver: "125",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Patrol Y62",
      year_of_issue: "2010-",
      body_style: "suv",
      vendor_code: "NS 31",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Nissan",
      model: "Qashqai J10",
      year_of_issue: "2007-2014",
      body_style: "suv",
      vendor_code: "NS 13",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Qashqai J11",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "NS 25",
      max_hor: "1800",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Rogue T32",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "NS 27",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Terrano",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "RN 13",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Tiida C11",
      year_of_issue: "2007-2014",
      body_style: "седан",
      vendor_code: "NS 23",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "Tiida C11",
      year_of_issue: "2007-2014",
      body_style: "хэтчбек",
      vendor_code: "NS 23",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "X-Trail T31",
      year_of_issue: "2007-2014",
      body_style: "suv",
      vendor_code: "NS 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Nissan",
      model: "X-Trail Т32",
      year_of_issue: "2014-",
      body_style: "suv",
      vendor_code: "NS 27",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "308",
      year_of_issue: "2008-2013",
      body_style: "хэтчбек",
      vendor_code: "PE 02",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "408",
      year_of_issue: "2013-",
      body_style: "седан",
      vendor_code: "PE 03",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "4007",
      year_of_issue: "2007-2012",
      body_style: "suv",
      vendor_code: "MI 21",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "4008",
      year_of_issue: "2012-",
      body_style: "suv",
      vendor_code: "MI 23",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Boxer",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "FA 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Boxer",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "FA 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Boxer III",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "FA 06",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Peugeot",
      model: "Expert III",
      year_of_issue: "2016-",
      body_style: "минивэн",
      vendor_code: "CN 02",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Partner II",
      year_of_issue: "2008-2019",
      body_style: "фургон (L1)",
      vendor_code: "PE 01",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Peugeot",
      model: "Traveller",
      year_of_issue: "2017-",
      body_style: "минивэн",
      vendor_code: "CN 02",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Arkana",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "RN 16",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Dokker",
      year_of_issue: "2017-",
      body_style: "универсал",
      vendor_code: "RN 17",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Duster I",
      year_of_issue: "2010-2015",
      body_style: "suv",
      vendor_code: "RN 13",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да*",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Duster II",
      year_of_issue: "2015-2021",
      body_style: "suv",
      vendor_code: "RN 13",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Fluence",
      year_of_issue: "2009-",
      body_style: "седан",
      vendor_code: "RN 09",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Kangoo II",
      year_of_issue: "2010-",
      body_style: "универсал",
      vendor_code: "RN 08",
      max_hor: "1350",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Kaptur",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "RN 14",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Logan I",
      year_of_issue: "2005-2014",
      body_style: "седан",
      vendor_code: "RN 15",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Logan I",
      year_of_issue: "2005-2014",
      body_style: "седан",
      vendor_code: "RN 12",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Logan II",
      year_of_issue: "2014-",
      body_style: "седан",
      vendor_code: "RN 15",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero I",
      year_of_issue: "2009-2014",
      body_style: "хэтчбек",
      vendor_code: "RN 06",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "RN 11",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "RN 15",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero Stepway II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "RN 11",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Sandero Stepway II",
      year_of_issue: "2014-",
      body_style: "хэтчбек",
      vendor_code: "RN 15",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Renault",
      model: "Symbol I",
      year_of_issue: "1998-2008",
      body_style: "седан",
      vendor_code: "RN 04",
      max_hor: "1150",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Seat",
      model: "Alhambra I (рестайлинг)",
      year_of_issue: "2000-2010",
      body_style: "минивэн",
      vendor_code: "VW 22",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Fabia 6Y",
      year_of_issue: "2000-2007",
      body_style: "седан",
      vendor_code: "SK 05",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Fabia 6Y",
      year_of_issue: "2000-2007",
      body_style: "универсал",
      vendor_code: "SK 05",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Fabia 5J",
      year_of_issue: "2008-2014",
      body_style: "универсал",
      vendor_code: "SK 05",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Karoq",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "SK 13",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Kodiaq",
      year_of_issue: "2017-",
      body_style: "suv",
      vendor_code: "SK 12",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia I",
      year_of_issue: "1996-2004",
      body_style: "хэтчбек",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia I",
      year_of_issue: "1996-2004",
      body_style: "универсал",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia Tour",
      year_of_issue: "2000-2010",
      body_style: "универсал",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia Tour",
      year_of_issue: "2004-2012",
      body_style: "универсал",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia II",
      year_of_issue: "2004-2013",
      body_style: "хэтчбек",
      vendor_code: "SK 09",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia II",
      year_of_issue: "2004-2013",
      body_style: "универсал",
      vendor_code: "SK 09",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia III",
      year_of_issue: "2013-2020",
      body_style: "хэтчбек",
      vendor_code: "SK 10",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Octavia III",
      year_of_issue: "2013-2020",
      body_style: "универсал",
      vendor_code: "SK 10",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Rapid",
      year_of_issue: "2013-",
      body_style: "хэтчбек",
      vendor_code: "SK 11",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Roomster",
      year_of_issue: "2006-2015",
      body_style: "минивэн",
      vendor_code: "SK 08",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Roomster",
      year_of_issue: "2006-2015",
      body_style: "фургон",
      vendor_code: "SK 08",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Superb I",
      year_of_issue: "2002-2008",
      body_style: "седан",
      vendor_code: "SK 06",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Skoda",
      model: "Yeti",
      year_of_issue: "2009-2018",
      body_style: "suv",
      vendor_code: "SK 07",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Actyon I",
      year_of_issue: "2006-2011",
      body_style: "suv",
      vendor_code: "SY 010",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Actyon II",
      year_of_issue: "2011-2015",
      body_style: "suv",
      vendor_code: "SY 011",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Actyon Sports",
      year_of_issue: "2006-2014",
      body_style: "пикап",
      vendor_code: "SY 008",
      max_hor: "750",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Korando",
      year_of_issue: "1997-2003",
      body_style: "suv",
      vendor_code: "TD 113",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Kyron",
      year_of_issue: "2005-2016",
      body_style: "suv",
      vendor_code: "SY 005",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Musso (вкл. Sport)",
      year_of_issue: "2002-",
      vendor_code: "SY 006",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Rexton Y200",
      year_of_issue: "2002-2006",
      body_style: "suv",
      vendor_code: "SY 005",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Rexton Y250",
      year_of_issue: "2006-2017",
      body_style: "suv",
      vendor_code: "SY 009",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "SsangYong",
      model: "Stavic",
      year_of_issue: "2013-",
      body_style: "suv",
      vendor_code: "SY 012",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester I",
      year_of_issue: "1997-2002",
      body_style: "suv",
      vendor_code: "SU 06",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester II",
      year_of_issue: "2002-2008",
      body_style: "suv",
      vendor_code: "SU 06",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester III",
      year_of_issue: "2008-2013",
      body_style: "suv",
      vendor_code: "SU 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Subaru",
      model: "Forester IV",
      year_of_issue: "2013-2018",
      body_style: "suv",
      vendor_code: "SU 07",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Grand Vitara",
      year_of_issue: "1998-2005",
      body_style: "suv",
      vendor_code: "SZ 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Grand Vitara XL7",
      year_of_issue: "2001-2006",
      body_style: "suv",
      vendor_code: "SZ 05",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Grand Vitara",
      year_of_issue: "2005-2016",
      body_style: "suv, 3 дв.",
      vendor_code: "SZ 08",
      max_hor: "1600",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Grand Vitara",
      year_of_issue: "2005-2016",
      body_style: "suv, 5 дв.",
      vendor_code: "SZ 06",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Jimny",
      year_of_issue: "1998-2018",
      body_style: "suv",
      vendor_code: "SZ 09",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Liana",
      year_of_issue: "2001-2007",
      body_style: "хэтчбек",
      vendor_code: "SZ 07",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "SX4 I (4WD)",
      year_of_issue: "2006-2013",
      body_style: "хэтчбек",
      vendor_code: "SZ 11",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "SX4 I",
      year_of_issue: "2006-2013",
      body_style: "седан",
      vendor_code: "SZ 10",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "SX4 II",
      year_of_issue: "2013-",
      body_style: "хэтчбек",
      vendor_code: "SZ 12",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Suzuki",
      model: "Vitara II",
      year_of_issue: "2005-",
      body_style: "suv",
      vendor_code: "SZ 08",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Amarok",
      year_of_issue: "2010-",
      body_style: "пикап",
      vendor_code: "VW 26",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара G",
    },
    {
      brand: "Volkswagen",
      model: "Amarok",
      year_of_issue: "2010-",
      body_style: "пикап",
      vendor_code: "VW 34",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Bora",
      year_of_issue: "1998-2004",
      body_style: "седан",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Bora",
      year_of_issue: "1998-2004",
      body_style: "универсал",
      vendor_code: "SK 04",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caddy II",
      year_of_issue: "2004-",
      body_style: "минивэн",
      vendor_code: "VW 21",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caravelle Т4",
      year_of_issue: "1990-2003",
      body_style: "минивэн",
      vendor_code: "VW 17",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caravelle Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caravelle Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caravelle Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Caravelle Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Crafter I (со ступенькой)",
      year_of_issue: "2006-2017",
      body_style: "фургон",
      vendor_code: "MB 04",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Volkswagen",
      model: "Crafter I (без ступеньки)",
      year_of_issue: "2006-2017",
      body_style: "фургон",
      vendor_code: "MB 06",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Volkswagen",
      model: "Golf IV",
      year_of_issue: "1997-2003",
      body_style: "хэтчбек",
      vendor_code: "SK 04",
      max_hor: "1400",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Golf IV",
      year_of_issue: "1997-2003",
      body_style: "универсал",
      vendor_code: "SK 04",
      max_hor: "1400",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Golf V",
      year_of_issue: "2003-2008",
      body_style: "хэтчбек",
      vendor_code: "VW 25",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Golf V Plus",
      year_of_issue: "2004-2008",
      body_style: "минивэн",
      vendor_code: "VW 25",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Golf VI",
      year_of_issue: "2008-2013",
      body_style: "хэтчбек",
      vendor_code: "VW 25",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Golf VI Plus",
      year_of_issue: "2008-2013",
      body_style: "минивэн",
      vendor_code: "VW 25",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Jetta VI",
      year_of_issue: "2011-2018",
      body_style: "седан",
      vendor_code: "VW 32",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Multivan Т4",
      year_of_issue: "1990-2003",
      body_style: "минивэн",
      vendor_code: "VW 17",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Multivan Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Multivan Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Multivan Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Multivan Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B5",
      year_of_issue: "1996-2005",
      body_style: "седан",
      vendor_code: "VW 30",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B5",
      year_of_issue: "1996-2005",
      body_style: "универсал",
      vendor_code: "VW 30",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B6",
      year_of_issue: "2005-2010",
      body_style: "седан",
      vendor_code: "VW 24",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B6",
      year_of_issue: "2005-2010",
      body_style: "универсал",
      vendor_code: "VW 24",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B7",
      year_of_issue: "2010-2015",
      body_style: "седан",
      vendor_code: "VW 31",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Passat B7",
      year_of_issue: "2010-2015",
      body_style: "универсал",
      vendor_code: "VW 31",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Pointer",
      year_of_issue: "2004-2009",
      body_style: "хэтчбек",
      vendor_code: "VW 18",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo V",
      year_of_issue: "2009-2018",
      body_style: "хэтчбек",
      vendor_code: "VW 27",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo sedan (профиль трубы круглый)",
      year_of_issue: "2010-",
      body_style: "седан",
      vendor_code: "VW 33",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo sedan (профиль трубы квадратный)",
      year_of_issue: "2010-",
      body_style: "седан",
      vendor_code: "VW 28",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo liftback (профиль трубы круглый)",
      year_of_issue: "2020-",
      body_style: "хэтчбек",
      vendor_code: "VW 33",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Polo liftback (профиль трубы квадратный)",
      year_of_issue: "2020-",
      body_style: "хэтчбек",
      vendor_code: "VW 28",
      max_hor: "750",
      max_ver: "50",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Sharan I (рестайлинг)",
      year_of_issue: "2000-2010",
      body_style: "минивэн",
      vendor_code: "VW 22",
      max_hor: "1200",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan I",
      year_of_issue: "2007-2016",
      body_style: "suv",
      vendor_code: "VW 35",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan I",
      year_of_issue: "2007-2016",
      body_style: "suv",
      vendor_code: "VW 23",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan II",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "VW 35",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Tiguan II",
      year_of_issue: "2016-",
      body_style: "suv",
      vendor_code: "SK 12",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Touareg I",
      year_of_issue: "2002-2010",
      body_style: "suv",
      vendor_code: "AU 05",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Touareg I",
      year_of_issue: "2002-2010",
      body_style: "suv",
      vendor_code: "VW 20",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Touareg II",
      year_of_issue: "2010-2018",
      body_style: "suv",
      vendor_code: "AU 05",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Transporter Т4",
      year_of_issue: "1990-2003",
      body_style: "минивэн",
      vendor_code: "VW 17",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Transporter Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Transporter Т5",
      year_of_issue: "2003-2015",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Transporter Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 36",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Transporter Т6",
      year_of_issue: "2015-",
      body_style: "минивэн",
      vendor_code: "VW 29",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volkswagen",
      model: "Vento",
      year_of_issue: "1992-1998",
      body_style: "седан",
      vendor_code: "VW 19",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "S40 II",
      year_of_issue: "2004-2014",
      body_style: "седан",
      vendor_code: "VL 04",
      max_hor: "1600",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "S60 I",
      year_of_issue: "2000-2009",
      body_style: "седан",
      vendor_code: "VL 06",
      max_hor: "1600",
      max_ver: "85",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "S60 II",
      year_of_issue: "2010-2019",
      body_style: "седан",
      vendor_code: "VL 05",
      max_hor: "1800",
      max_ver: "80",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "V50",
      year_of_issue: "2004-2012",
      body_style: "универсал",
      vendor_code: "VL 04",
      max_hor: "1600",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "V60 I",
      year_of_issue: "2010-2019",
      body_style: "универсал",
      vendor_code: "VL 05",
      max_hor: "1800",
      max_ver: "80",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "ХС60 I",
      year_of_issue: "2008-2017",
      body_style: "suv",
      vendor_code: "VL 02",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "ХС70 III",
      year_of_issue: "2007-2016",
      body_style: "suv",
      vendor_code: "VL 03",
      max_hor: "2000",
      max_ver: "90",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Volvo",
      model: "ХС90 I",
      year_of_issue: "2003-2014",
      body_style: "suv",
      vendor_code: "VL 01",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Alphard II",
      year_of_issue: "2008-2015",
      body_style: "минивэн",
      vendor_code: "TY 39",
      max_hor: "2000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Camry 40",
      year_of_issue: "2006-2011",
      body_style: "седан",
      vendor_code: "TY 17",
      max_hor: "1800",
      max_ver: "80",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Camry 50 (55)",
      year_of_issue: "2011-2017",
      body_style: "седан",
      vendor_code: "TY 17",
      max_hor: "1800",
      max_ver: "80",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E120",
      year_of_issue: "2002-2007",
      body_style: "седан",
      vendor_code: "TY 33",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E120",
      year_of_issue: "2002-2007",
      body_style: "универсал",
      vendor_code: "TY 30",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E130",
      year_of_issue: "2002-2007",
      body_style: "седан",
      vendor_code: "TY 33",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E130",
      year_of_issue: "2002-2007",
      body_style: "универсал",
      vendor_code: "TY 30",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Corolla E150",
      year_of_issue: "2007-2013",
      body_style: "седан",
      vendor_code: "TY 18",
      max_hor: "1350",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Fortuner II",
      year_of_issue: "2018-",
      body_style: "suv",
      vendor_code: "TY 46",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "Highlander XU40",
      year_of_issue: "2007-2010",
      body_style: "suv",
      vendor_code: "TY 32",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Highlander XU40+",
      year_of_issue: "2010-2014",
      body_style: "suv",
      vendor_code: "TY 38",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "Highlander XU50",
      year_of_issue: "2014-2020",
      body_style: "suv",
      vendor_code: "TY 45",
      max_hor: "2200",
      max_ver: "120",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "Hilux VII (c силовым брусом)",
      year_of_issue: "2005-2010",
      body_style: "пикап",
      vendor_code: "TY 44",
      max_hor: "2800",
      max_ver: "120",
      bumper_cutout: "нет",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "Hilux VII",
      year_of_issue: "2005-2015",
      body_style: "пикап",
      vendor_code: "TY 36",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Hilux VII (c силовым брусом)",
      year_of_issue: "2005-2015",
      body_style: "пикап",
      vendor_code: "TY 27",
      max_hor: "1500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Hilux VIII",
      year_of_issue: "2015-",
      body_style: "пикап",
      vendor_code: "TY 40",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 76",
      year_of_issue: "1984-",
      body_style: "suv",
      vendor_code: "TY 35",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара E",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 60, 70, 76, 80, 105",
      year_of_issue: "1984-",
      body_style: "suv",
      vendor_code: "TY 05",
      max_hor: "750",
      max_ver: "50",
      type_of_ball: "вставка под квадрат",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 120",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "TY 42",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 120",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "TY 21",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 120",
      year_of_issue: "2003-2009",
      body_style: "suv",
      vendor_code: "TY 26",
      max_hor: "2800",
      max_ver: "130",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 150",
      year_of_issue: "2009-",
      body_style: "suv",
      vendor_code: "TY 42",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 150",
      year_of_issue: "2009-",
      body_style: "suv",
      vendor_code: "TY 26",
      max_hor: "2800",
      max_ver: "130",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 200",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "TY 28",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Land Cruiser 200",
      year_of_issue: "2007-",
      body_style: "suv",
      vendor_code: "TY 25",
      max_hor: "3500",
      max_ver: "140",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Toyota",
      model: "RAV4 XA20",
      year_of_issue: "2000-2006",
      body_style: "suv",
      vendor_code: "TY 16",
      max_hor: "1000",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 XA30 (з/к на двери)",
      year_of_issue: "2009-2013",
      body_style: "suv",
      vendor_code: "TY 23",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 IV",
      year_of_issue: "2013-2019",
      body_style: "suv",
      vendor_code: "TY 34",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 V",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "TY 48",
      max_hor: "1500",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "RAV4 V",
      year_of_issue: "2019-",
      body_style: "suv",
      vendor_code: "TY 48B",
      max_hor: "1500",
      max_ver: "60",
      bumper_cutout: "нет",
      type_of_ball: "тип шара  E/F/G",
    },
    {
      brand: "Toyota",
      model: "Sienna III (Япония)",
      year_of_issue: "2011-",
      body_style: "минивэн",
      vendor_code: "TY 43",
      max_hor: "1800",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Toyota",
      model: "Yaris Verso",
      year_of_issue: "2000-2004",
      body_style: "хэтчбек",
      vendor_code: "TY 31",
      max_hor: "1000",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Opel",
      model: "Zafira Tourer C",
      year_of_issue: "2012-2019",
      body_style: "минивэн",
      vendor_code: "OP 07",
      max_hor: "1500",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "С4 II",
      year_of_issue: "2013-",
      body_style: "седан",
      vendor_code: "CN 01",
      max_hor: "1250",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "Jumper I",
      year_of_issue: "1994-2006",
      body_style: "фургон",
      vendor_code: "FA 05",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "Jumper II",
      year_of_issue: "2006-",
      body_style: "фургон",
      vendor_code: "FA 06",
      max_hor: "2000",
      max_ver: "100",
      bumper_cutout: "да",
      type_of_ball: "тип шара F",
    },
    {
      brand: "Citroen",
      model: "Jumpy III",
      year_of_issue: "2016-",
      body_style: "минивэн",
      vendor_code: "CN 02",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Citroen",
      model: "Spacetourer",
      year_of_issue: "2017-",
      body_style: "минивэн",
      vendor_code: "CN 02",
      max_hor: "2500",
      max_ver: "100",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2011-2013",
      body_style: "седан",
      vendor_code: "VAZ-61",
      max_hor: "800",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара H",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2011-2018",
      body_style: "седан",
      vendor_code: "VAZ-61",
      max_hor: "800",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Granta",
      year_of_issue: "2011-2018",
      body_style: "хэтчбек",
      vendor_code: "VAZ-68",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Largus",
      year_of_issue: "2012-",
      body_style: "универсал",
      vendor_code: "RN 03",
      max_hor: "1300",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Niva",
      year_of_issue: "1977-",
      body_style: "хэтчбек",
      vendor_code: "VAZ-24",
      max_hor: "800",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Niva",
      year_of_issue: "1977-",
      body_style: "хэтчбек",
      vendor_code: "VAZ-51",
      max_hor: "800",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Vesta",
      year_of_issue: "2016-",
      body_style: "седан",
      vendor_code: "VAZ-65",
      max_hor: "900",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Vesta",
      year_of_issue: "2016-",
      body_style: "универсал",
      vendor_code: "VAZ-70",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "Vesta Cross",
      year_of_issue: "2018-2020",
      body_style: "универсал",
      vendor_code: "VAZ-70",
      max_hor: "1100",
      max_ver: "75",
      bumper_cutout: "да",
      type_of_ball: "тип шара A",
    },
    {
      brand: "Lada",
      model: "X-Ray",
      year_of_issue: "2016-",
      body_style: "универсал",
      vendor_code: "VAZ-66",
      max_hor: "1100",
      max_ver: "50",
      bumper_cutout: "нет",
      type_of_ball: "тип шара A",
    },
  ],
};
