import React from "react";
import Head from "next/head";
import {
  CarouselModule,
  Footer,
  SelectionBlock,
  Recommendations,
} from "components";

import styles from "../styles/Home.module.scss";

const Home = () => {
  return (
    <>
      <Head>
        <title>Главная || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.mainBlock}>
          <div className={styles.leftBlock}>
            <div>
              <span className={styles.mainText}>
                Towbars - интернет-магазин по продаже фаркопов, <br /> электрики
                (универсальной, штатной) и <br />
                дополнительных аксессуаров
              </span>
            </div>
            <SelectionBlock />
          </div>
          <div className={styles.rightBlock}>
            <img src="static/images/towbar-west.png" alt="towbar-westfalia" />
          </div>
        </div>
        <CarouselModule />
        <Recommendations />
        <Footer />
      </div>
    </>
  );
};

export default Home;
