import React from "react";
import Head from "next/head";
import { ProfilePageBlock } from "components";

const FavoritesPage = () => {
  return (
    <>
      <Head>
        <title>Избранное || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePageBlock link={"favorites"}/>
    </>
  );
};

export default FavoritesPage;
