import React from "react";
import Head from "next/head";
import { ProfilePageBlock } from "components";

const OrdersHistoryPage = () => {
  return (
    <>
      <Head>
        <title>История заказов || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePageBlock link={"orders-history"} />
    </>
  );
};

export default OrdersHistoryPage;
