import React from "react";
import Head from "next/head";
import AdminOrders from "components/AdminPanel/Orders/AdminOrders";

const AdminOrdersPage = () => {
  return (
    <>
      <Head>
        <title>Управление заказами || Админ-панель</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminOrders />
    </>
  );
};

export default AdminOrdersPage;
