import React from "react";
import Head from "next/head";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Контакты || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Контакты</div>
    </>
  );
};

export default Contacts;
