import React from "react";
import Head from "next/head";
import { ContactsBlock, Footer } from "components";

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Контакты || Towbars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactsBlock />
      <Footer />
    </>
  );
};

export default Contacts;
